// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vcore.h for the primary calling header

#ifndef VERILATED_VCORE___024ROOT_H_
#define VERILATED_VCORE___024ROOT_H_  // guard

#include "verilated.h"


class Vcore__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vcore___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(io_inst_done,0,0);
        CData/*4:0*/ core__DOT___WBU_io_out_addr;
        CData/*0:0*/ core__DOT___WBU_io_out_en;
        CData/*0:0*/ core__DOT___LSU_io_out_valid;
        CData/*0:0*/ core__DOT___LSU_io_out_bits_rd_en;
        CData/*4:0*/ core__DOT___LSU_io_out_bits_rd_addr;
        CData/*0:0*/ core__DOT___LSU_io_axi_r_ready;
        CData/*3:0*/ core__DOT___LSU_io_axi_w_bits_strb;
        CData/*0:0*/ core__DOT___LSU_io_axi_b_ready;
        CData/*0:0*/ core__DOT___EXU_io_out_valid;
        CData/*0:0*/ core__DOT___EXU_io_out_bits_rd_en;
        CData/*4:0*/ core__DOT___EXU_io_out_bits_rd_addr;
        CData/*0:0*/ core__DOT___EXU_io_out_bits_mem_wen;
        CData/*0:0*/ core__DOT___EXU_io_out_bits_mem_ren;
        CData/*3:0*/ core__DOT___EXU_io_out_bits_mem_len;
        CData/*0:0*/ core__DOT___EXU_io_out_bits_unsign_en;
        CData/*0:0*/ core__DOT___EXU_io_pcCtrl_pcSel;
        CData/*0:0*/ core__DOT___EXU_io_in_ready;
        CData/*0:0*/ core__DOT___IDU_io_in_ready;
        CData/*0:0*/ core__DOT___IDU_io_out_valid;
        CData/*0:0*/ core__DOT___IDU_io_out_bits_rd_en;
        CData/*4:0*/ core__DOT___IDU_io_out_bits_opcode;
        CData/*0:0*/ core__DOT___IDU_io_out_bits_rs2_en;
        CData/*0:0*/ core__DOT___IDU_io_out_bits_unsign_en;
        CData/*0:0*/ core__DOT___IDU_io_out_bits_lsu_en;
        CData/*0:0*/ core__DOT___IDU_io_out_bits_mw_en;
        CData/*3:0*/ core__DOT___IDU_io_out_bits_mlen;
        CData/*0:0*/ core__DOT___IDU_io_out_bits_branch_en;
        CData/*0:0*/ core__DOT___IFU_io_out_valid;
        CData/*0:0*/ core__DOT___IFU_io_axi_ar_valid;
        CData/*0:0*/ core__DOT__validReg;
        CData/*0:0*/ core__DOT__producerFire;
        CData/*0:0*/ core__DOT__validReg_1;
        CData/*1:0*/ core__DOT__dataReg_1_resp;
        CData/*0:0*/ core__DOT___IFU_io_axi_r_valid_T;
        CData/*0:0*/ core__DOT__validReg_5;
        CData/*0:0*/ core__DOT__readyForProducer_5;
        CData/*0:0*/ core__DOT__producerFire_5;
        CData/*0:0*/ core__DOT__validReg_6;
        CData/*1:0*/ core__DOT__dataReg_6_resp;
        CData/*0:0*/ core__DOT__validReg_7;
        CData/*0:0*/ core__DOT__readyForProducer_7;
        CData/*0:0*/ core__DOT__producerFire_7;
        CData/*0:0*/ core__DOT__validReg_8;
        CData/*0:0*/ core__DOT__readyForProducer_8;
        CData/*0:0*/ core__DOT__producerFire_8;
        CData/*0:0*/ core__DOT__validReg_9;
        CData/*3:0*/ core__DOT__dataReg_9_strb;
        CData/*0:0*/ core__DOT__readyForProducer_9;
        CData/*0:0*/ core__DOT__producerFire_9;
        CData/*0:0*/ core__DOT__validReg_10;
        CData/*0:0*/ core__DOT__readyForProducer_10;
        CData/*0:0*/ core__DOT__validReg_11;
        CData/*4:0*/ core__DOT__dataReg_11_rd_addr;
        CData/*0:0*/ core__DOT__dataReg_11_rd_en;
        CData/*4:0*/ core__DOT__dataReg_11_opcode;
        CData/*0:0*/ core__DOT__dataReg_11_rs2_en;
        CData/*0:0*/ core__DOT__dataReg_11_unsign_en;
        CData/*0:0*/ core__DOT__dataReg_11_csr_en;
        CData/*0:0*/ core__DOT__dataReg_11_lsu_en;
        CData/*0:0*/ core__DOT__dataReg_11_mw_en;
        CData/*3:0*/ core__DOT__dataReg_11_mlen;
    };
    struct {
        CData/*0:0*/ core__DOT__dataReg_11_branch_en;
        CData/*0:0*/ core__DOT__dataReg_11_jump_en;
        CData/*0:0*/ core__DOT__dataReg_11_jalr_en;
        CData/*0:0*/ core__DOT__dataReg_11_auipc_en;
        CData/*0:0*/ core__DOT__producerFire_11;
        CData/*0:0*/ core__DOT__validReg_12;
        CData/*0:0*/ core__DOT__dataReg_12_rd_en;
        CData/*4:0*/ core__DOT__dataReg_12_rd_addr;
        CData/*0:0*/ core__DOT__dataReg_12_mem_wen;
        CData/*0:0*/ core__DOT__dataReg_12_mem_ren;
        CData/*3:0*/ core__DOT__dataReg_12_mem_len;
        CData/*0:0*/ core__DOT__dataReg_12_unsign_en;
        CData/*0:0*/ core__DOT___LSU_io_in_valid_T;
        CData/*0:0*/ core__DOT__producerFire_12;
        CData/*0:0*/ core__DOT__validReg_13;
        CData/*0:0*/ core__DOT__dataReg_13_rd_en;
        CData/*4:0*/ core__DOT__dataReg_13_rd_addr;
        CData/*0:0*/ core__DOT__consumerFire_1;
        CData/*0:0*/ core__DOT____Vcellinp__EXU__io_in_bits_jalr_en;
        CData/*0:0*/ core__DOT____Vcellinp__EXU__io_in_bits_jump_en;
        CData/*0:0*/ core__DOT____Vcellinp__EXU__io_in_bits_branch_en;
        CData/*4:0*/ core__DOT____Vcellinp__EXU__io_in_bits_opcode;
        CData/*0:0*/ core__DOT____Vcellinp__LSU__io_in_bits_mem_ren;
        CData/*0:0*/ core__DOT____Vcellinp__LSU__io_in_bits_mem_wen;
        CData/*4:0*/ core__DOT____Vcellinp__LSU__io_in_bits_rd_addr;
        CData/*0:0*/ core__DOT____Vcellinp__LSU__io_in_bits_rd_en;
        CData/*0:0*/ core__DOT__Fsram__DOT__r_state;
        CData/*0:0*/ core__DOT__Fsram__DOT___write_backend_done;
        CData/*0:0*/ core__DOT__Fsram__DOT___read_backend_done;
        CData/*0:0*/ core__DOT__Fsram__DOT___read_backend_io_en_T;
        CData/*0:0*/ core__DOT__Fsram__DOT__write_backend_io_en_REG;
        CData/*0:0*/ core__DOT__Fsram__DOT__r_valid_reg;
        CData/*1:0*/ core__DOT__Fsram__DOT__r_bits_reg_resp;
        CData/*0:0*/ core__DOT__Fsram__DOT__w_state;
        CData/*3:0*/ core__DOT__Fsram__DOT__write_backend_io_w_strb_REG;
        CData/*0:0*/ core__DOT__Fsram__DOT__b_valid_reg;
        CData/*1:0*/ core__DOT__Fsram__DOT__b_bits_reg_resp;
        CData/*0:0*/ core__DOT__Fsram__DOT___GEN;
        CData/*0:0*/ core__DOT__Fsram__DOT___GEN_0;
        CData/*2:0*/ core__DOT__Fsram__DOT__read_backend__DOT__delay;
        CData/*0:0*/ core__DOT__Lsram__DOT__r_state;
        CData/*0:0*/ core__DOT__Lsram__DOT___write_backend_done;
        CData/*0:0*/ core__DOT__Lsram__DOT___read_backend_done;
        CData/*0:0*/ core__DOT__Lsram__DOT___read_backend_io_en_T;
        CData/*0:0*/ core__DOT__Lsram__DOT__write_backend_io_en_REG;
        CData/*0:0*/ core__DOT__Lsram__DOT__r_valid_reg;
        CData/*1:0*/ core__DOT__Lsram__DOT__r_bits_reg_resp;
        CData/*0:0*/ core__DOT__Lsram__DOT__w_state;
        CData/*3:0*/ core__DOT__Lsram__DOT__write_backend_io_w_strb_REG;
        CData/*0:0*/ core__DOT__Lsram__DOT__b_valid_reg;
        CData/*1:0*/ core__DOT__Lsram__DOT__b_bits_reg_resp;
        CData/*0:0*/ core__DOT__Lsram__DOT___GEN;
        CData/*0:0*/ core__DOT__Lsram__DOT___GEN_0;
        CData/*0:0*/ core__DOT__Lsram__DOT___write_backend_io_en_T;
        CData/*0:0*/ core__DOT__Lsram__DOT___write_backend_io_en_T_1;
        CData/*2:0*/ core__DOT__Lsram__DOT__read_backend__DOT__delay;
        CData/*0:0*/ core__DOT__IFU__DOT__axi_r_decoupled_valid;
        CData/*0:0*/ core__DOT__IFU__DOT__ar_request_in_flight;
        CData/*0:0*/ core__DOT__IFU__DOT__validReg;
        CData/*0:0*/ core__DOT__IFU__DOT__readyForProducer;
        CData/*0:0*/ core__DOT__IFU__DOT__consumerFire;
        CData/*0:0*/ core__DOT__IFU__DOT___GEN;
        CData/*0:0*/ core__DOT__IFU__DOT__producerFire;
        CData/*7:0*/ core__DOT__IDU__DOT___decodedBundle_andMatrixOutputs_T;
    };
    struct {
        CData/*7:0*/ core__DOT__IDU__DOT___decodedBundle_andMatrixOutputs_T_1;
        CData/*7:0*/ core__DOT__IDU__DOT___decodedBundle_andMatrixOutputs_T_2;
        CData/*7:0*/ core__DOT__IDU__DOT___decodedBundle_andMatrixOutputs_T_3;
        CData/*5:0*/ core__DOT__IDU__DOT___decodedBundle_andMatrixOutputs_T_6;
        CData/*6:0*/ core__DOT__IDU__DOT___decodedBundle_andMatrixOutputs_T_7;
        CData/*7:0*/ core__DOT__IDU__DOT___decodedBundle_andMatrixOutputs_T_9;
        CData/*7:0*/ core__DOT__IDU__DOT___decodedBundle_andMatrixOutputs_T_14;
        CData/*6:0*/ core__DOT__IDU__DOT___decodedBundle_andMatrixOutputs_T_18;
        CData/*7:0*/ core__DOT__IDU__DOT___decodedBundle_andMatrixOutputs_T_25;
        CData/*7:0*/ core__DOT__IDU__DOT___decodedBundle_andMatrixOutputs_T_38;
        CData/*0:0*/ core__DOT__IDU__DOT____VdfgRegularize_h94ddb430_0_27;
        CData/*0:0*/ core__DOT__IDU__DOT____VdfgRegularize_h94ddb430_0_32;
        CData/*0:0*/ core__DOT__IDU__DOT____VdfgRegularize_h94ddb430_0_33;
        CData/*0:0*/ core__DOT__IDU__DOT____VdfgRegularize_h94ddb430_0_34;
        CData/*0:0*/ core__DOT__IDU__DOT____VdfgRegularize_h94ddb430_0_35;
        CData/*0:0*/ core__DOT__IDU__DOT____VdfgRegularize_h94ddb430_0_36;
        CData/*0:0*/ core__DOT__IDU__DOT____VdfgRegularize_h94ddb430_0_38;
        CData/*0:0*/ core__DOT__IDU__DOT____VdfgRegularize_h94ddb430_0_40;
        CData/*0:0*/ core__DOT__IDU__DOT____VdfgRegularize_h94ddb430_0_41;
        CData/*0:0*/ core__DOT__IDU__DOT____VdfgRegularize_h94ddb430_0_42;
        CData/*0:0*/ core__DOT__IDU__DOT____VdfgRegularize_h94ddb430_0_44;
        CData/*0:0*/ core__DOT__IDU__DOT____VdfgRegularize_h94ddb430_0_47;
        CData/*2:0*/ core__DOT__IDU__DOT____VdfgRegularize_h94ddb430_0_49;
        CData/*1:0*/ core__DOT__IDU__DOT____VdfgRegularize_h94ddb430_0_50;
        CData/*5:0*/ core__DOT__IDU__DOT____VdfgRegularize_h94ddb430_0_51;
        CData/*1:0*/ core__DOT__IDU__DOT____VdfgRegularize_h94ddb430_0_52;
        CData/*0:0*/ core__DOT__EXU__DOT____VdfgRegularize_h9d365bda_0_1;
        CData/*0:0*/ core__DOT__RF__DOT___GEN;
        CData/*2:0*/ core__DOT__LSU__DOT__state;
        CData/*0:0*/ core__DOT__LSU__DOT__e2l_reg_rd_en;
        CData/*4:0*/ core__DOT__LSU__DOT__e2l_reg_rd_addr;
        CData/*3:0*/ core__DOT__LSU__DOT__e2l_reg_mem_len;
        CData/*0:0*/ core__DOT__LSU__DOT__e2l_reg_unsign_en;
        CData/*0:0*/ core__DOT__LSU__DOT__is_passthrough;
        CData/*0:0*/ core__DOT__LSU__DOT__io_in_ready_0;
        CData/*0:0*/ core__DOT__LSU__DOT___GEN_1;
        CData/*0:0*/ core__DOT__LSU__DOT__io_axi_ar_valid_0;
        CData/*0:0*/ core__DOT__LSU__DOT___GEN_2;
        CData/*0:0*/ core__DOT__LSU__DOT___GEN_3;
        CData/*0:0*/ core__DOT__LSU__DOT___GEN_4;
        CData/*0:0*/ core__DOT__LSU__DOT__io_axi_w_valid_0;
        CData/*0:0*/ core__DOT__LSU__DOT___GEN_5;
        CData/*0:0*/ core__DOT__LSU__DOT___GEN_6;
        CData/*0:0*/ core__DOT__LSU__DOT___GEN_7;
        CData/*0:0*/ core__DOT__LSU__DOT____VdfgRegularize_ha7d0a824_0_3;
        CData/*0:0*/ core__DOT__LSU__DOT____VdfgRegularize_ha7d0a824_0_4;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clock__0;
        CData/*0:0*/ __VactContinue;
        SData/*8:0*/ core__DOT__IDU__DOT___decodedBundle_andMatrixOutputs_T_8;
        SData/*15:0*/ core__DOT__IDU__DOT___decodedBundle_andMatrixOutputs_T_11;
        SData/*12:0*/ core__DOT__IDU__DOT___decodedBundle_andMatrixOutputs_T_12;
        SData/*9:0*/ core__DOT__IDU__DOT___decodedBundle_andMatrixOutputs_T_17;
        SData/*8:0*/ core__DOT__IDU__DOT___decodedBundle_andMatrixOutputs_T_39;
        SData/*15:0*/ core__DOT__IDU__DOT___decodedBundle_andMatrixOutputs_T_40;
        VL_OUT(io_debugPC,31,0);
        VL_OUT(io_debugInst,31,0);
        VL_OUT(io_debugin1,31,0);
        VL_OUT(io_debugin2,31,0);
        VL_OUT(io_debugout1,31,0);
        VL_OUT(io_debugmemaddr,31,0);
        VL_OUT(io_debugmemdata,31,0);
        IData/*31:0*/ core__DOT___LSU_io_out_bits_rd_data;
        IData/*31:0*/ core__DOT___LSU_io_axi_w_bits_data;
    };
    struct {
        IData/*31:0*/ core__DOT___EXU_io_out_bits_mem_wdata;
        IData/*31:0*/ core__DOT___IDU_io_out_bits_pc;
        IData/*31:0*/ core__DOT__dataReg_addr;
        IData/*31:0*/ core__DOT__dataReg_1_data;
        IData/*31:0*/ core__DOT__dataReg_5_addr;
        IData/*31:0*/ core__DOT__dataReg_6_data;
        IData/*31:0*/ core__DOT__dataReg_7_addr;
        IData/*31:0*/ core__DOT__dataReg_9_data;
        IData/*31:0*/ core__DOT__dataReg_10_inst;
        IData/*31:0*/ core__DOT__dataReg_10_pc;
        IData/*31:0*/ core__DOT__dataReg_11_rs1_data;
        IData/*31:0*/ core__DOT__dataReg_11_rs2_data;
        IData/*31:0*/ core__DOT__dataReg_11_pc;
        IData/*31:0*/ core__DOT__dataReg_12_rd_data;
        IData/*31:0*/ core__DOT__dataReg_12_mem_addr;
        IData/*31:0*/ core__DOT__dataReg_12_mem_wdata;
        IData/*31:0*/ core__DOT__dataReg_13_rd_data;
        IData/*31:0*/ core__DOT____Vcellinp__IFU__io_axi_r_bits_data;
        IData/*31:0*/ core__DOT____Vcellinp__IDU__io_in_bits_inst;
        IData/*31:0*/ core__DOT____Vcellinp__EXU__io_in_bits_pc;
        IData/*31:0*/ core__DOT____Vcellinp__LSU__io_in_bits_rd_data;
        IData/*31:0*/ core__DOT____Vcellinp__WBU__io_in_bits_rd_data;
        IData/*31:0*/ core__DOT__Fsram__DOT__r_bits_reg_data;
        IData/*31:0*/ core__DOT__Fsram__DOT__write_backend_io_aw_addr_REG;
        IData/*31:0*/ core__DOT__Fsram__DOT__write_backend_io_w_data_REG;
        IData/*31:0*/ core__DOT__Fsram__DOT__read_backend__DOT__r_data_reg;
        IData/*31:0*/ core__DOT__Fsram__DOT__read_backend__DOT__r_data_comb;
        IData/*31:0*/ core__DOT__Lsram__DOT__r_bits_reg_data;
        IData/*31:0*/ core__DOT__Lsram__DOT__write_backend_io_aw_addr_REG;
        IData/*31:0*/ core__DOT__Lsram__DOT__write_backend_io_w_data_REG;
        IData/*31:0*/ core__DOT__Lsram__DOT__read_backend__DOT__r_data_reg;
        IData/*31:0*/ core__DOT__Lsram__DOT__read_backend__DOT__r_data_comb;
        IData/*31:0*/ core__DOT__IFU__DOT__pc;
        IData/*31:0*/ core__DOT__IFU__DOT__pc_in_flight;
        IData/*31:0*/ core__DOT__IFU__DOT__dataReg_inst;
        IData/*31:0*/ core__DOT__IFU__DOT__dataReg_pc;
        IData/*31:0*/ core__DOT__EXU__DOT___alu_io_out;
        IData/*31:0*/ core__DOT__EXU__DOT____Vcellinp__alu__io_in2;
        IData/*31:0*/ core__DOT__EXU__DOT____Vcellinp__alu__io_in1;
        IData/*31:0*/ core__DOT__LSU__DOT__e2l_reg_rd_data;
        IData/*31:0*/ core__DOT__LSU__DOT__e2l_reg_mem_addr;
        IData/*31:0*/ core__DOT__LSU__DOT__e2l_reg_mem_wdata;
        IData/*31:0*/ __Vtask_core__DOT__Fsram__DOT__read_backend__DOT__mem_read__0__r_data;
        IData/*31:0*/ __Vtask_core__DOT__Lsram__DOT__read_backend__DOT__mem_read__2__r_data;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ core__DOT__dataReg_11_imm;
        QData/*63:0*/ core__DOT____Vcellinp__EXU__io_in_bits_imm;
        QData/*63:0*/ core__DOT__IDU__DOT__casez_tmp;
        QData/*63:0*/ core__DOT__RF__DOT__rf_0;
        QData/*63:0*/ core__DOT__RF__DOT__rf_1;
        QData/*63:0*/ core__DOT__RF__DOT__rf_2;
        QData/*63:0*/ core__DOT__RF__DOT__rf_3;
        QData/*63:0*/ core__DOT__RF__DOT__rf_4;
        QData/*63:0*/ core__DOT__RF__DOT__rf_5;
        QData/*63:0*/ core__DOT__RF__DOT__rf_6;
        QData/*63:0*/ core__DOT__RF__DOT__rf_7;
        QData/*63:0*/ core__DOT__RF__DOT__rf_8;
        QData/*63:0*/ core__DOT__RF__DOT__rf_9;
        QData/*63:0*/ core__DOT__RF__DOT__rf_10;
        QData/*63:0*/ core__DOT__RF__DOT__rf_11;
        QData/*63:0*/ core__DOT__RF__DOT__rf_12;
        QData/*63:0*/ core__DOT__RF__DOT__rf_13;
        QData/*63:0*/ core__DOT__RF__DOT__rf_14;
        QData/*63:0*/ core__DOT__RF__DOT__rf_15;
    };
    struct {
        QData/*63:0*/ core__DOT__RF__DOT__rf_16;
        QData/*63:0*/ core__DOT__RF__DOT__rf_17;
        QData/*63:0*/ core__DOT__RF__DOT__rf_18;
        QData/*63:0*/ core__DOT__RF__DOT__rf_19;
        QData/*63:0*/ core__DOT__RF__DOT__rf_20;
        QData/*63:0*/ core__DOT__RF__DOT__rf_21;
        QData/*63:0*/ core__DOT__RF__DOT__rf_22;
        QData/*63:0*/ core__DOT__RF__DOT__rf_23;
        QData/*63:0*/ core__DOT__RF__DOT__rf_24;
        QData/*63:0*/ core__DOT__RF__DOT__rf_25;
        QData/*63:0*/ core__DOT__RF__DOT__rf_26;
        QData/*63:0*/ core__DOT__RF__DOT__rf_27;
        QData/*63:0*/ core__DOT__RF__DOT__rf_28;
        QData/*63:0*/ core__DOT__RF__DOT__rf_29;
        QData/*63:0*/ core__DOT__RF__DOT__rf_30;
        QData/*63:0*/ core__DOT__RF__DOT__rf_31;
        QData/*63:0*/ core__DOT__RF__DOT__casez_tmp;
        QData/*63:0*/ core__DOT__RF__DOT__casez_tmp_0;
        VlUnpacked<CData/*0:0*/, 2> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VactTriggered;
    VlTriggerVec<1> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vcore__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vcore___024root(Vcore__Syms* symsp, const char* v__name);
    ~Vcore___024root();
    VL_UNCOPYABLE(Vcore___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
